spring.application.name=User-Api28mar26

server.port= 8082
spring.datasource.url=jdbc:mysql://localhost:3306/userApi_28mar26
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true